### ISSUE TITLE
Update Model Class Diagram in Developer Guide

### ISSUE THREAD

**Issue by elliottan** [CS2103-AY1819S1-F10-1/main#26]
We need to add new classes to represent entities in the OASIS system.
- [ ] Rename Person class to Employee.
- [ ] Add a new Manager class that inherits from Employee (a manager is an employee with additional rights in the system).

Please add on what else we may need! Perhaps a Leave class?

**Comment by ChooJeremy** [comment]
I think this is no longer required in our case?
Renaming Person class is going to be a PITA and Person kind of works just fine -  "Employees are people"
Manager class is no longer required due to permissions system?
