### ISSUE TITLE
As an Employee, I can log in

### ISSUE THREAD

**Issue by ChooJeremy** [CS2103-AY1819S1-F10-1/main#64]
So that I can access the features of the system

**Comment by ChooJeremy** [comment]
Login page implemented, 1.3 will include functionality to verify username/password

**Comment by parvathy-sudhir-pillai** [comment]
Hi Jeremy,

Regarding your question about storing the logged in user's information, Prof. Damith made a suggestion that you can have a `User` class. The `loggedInUser` is more likely to be a variable containing a reference to a `User` object. The loggedInUser interacts through the ModelManager as we discussed.

Regards,
Parvathy

**Comment by ChooJeremy** [comment]
@parvathy-sudhir-pillai 

Thanks! Would the user class simply store a reference to the Person object? it would just be a framework for in the event that we wanted to add more variables specific to the logged in user?
